
# after creating the pod, you can attach it to vs code using the kubernetes extension

apiVersion: v1
kind: Pod
metadata:
  name: tommy-notebook
spec:
  containers:
  - name: tommy-notebook
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
    command: ["sh", "-c", "sudo apt-get update && pip3 install torch torchvision torchaudio && jupyter notebook --ip='0.0.0.0' && sleep infinity"]
    resources:
      limits:
        memory: 20Gi
        cpu: "16"
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        cpu: "2"
        nvidia.com/gpu: 1

        # Uncomment Section to mount a PVC

        #   volumeMounts:
        #   - mountPath: /pvcvolume
        #     name: pvc
        # restartPolicy: Never
        # volumes:
        # - name: pvc
        #   persistentVolumeClaim:
        #     claimName: j-carla